// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPGS37tqAEaUwa_tiOhnv2qt3osRodkT0',
    appId: '1:170598160506:web:f81fe13d12f3f5f92743c3',
    messagingSenderId: '170598160506',
    projectId: 'vibetalk-1994d',
    authDomain: 'vibetalk-1994d.firebaseapp.com',
    storageBucket: 'vibetalk-1994d.firebasestorage.app',
    measurementId: 'G-F244PYB43J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtjCPjFfUhpI1MSG8sUoa60TGDLS1XbcM',
    appId: '1:170598160506:android:747804992d5b6abd2743c3',
    messagingSenderId: '170598160506',
    projectId: 'vibetalk-1994d',
    storageBucket: 'vibetalk-1994d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFZkrmlVvbG63Bs8LTNw-2J7CvcO08QFE',
    appId: '1:170598160506:ios:ff122635808e922e2743c3',
    messagingSenderId: '170598160506',
    projectId: 'vibetalk-1994d',
    storageBucket: 'vibetalk-1994d.firebasestorage.app',
    iosBundleId: 'com.igz.vibetalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFZkrmlVvbG63Bs8LTNw-2J7CvcO08QFE',
    appId: '1:170598160506:ios:ff122635808e922e2743c3',
    messagingSenderId: '170598160506',
    projectId: 'vibetalk-1994d',
    storageBucket: 'vibetalk-1994d.firebasestorage.app',
    iosBundleId: 'com.igz.vibetalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPGS37tqAEaUwa_tiOhnv2qt3osRodkT0',
    appId: '1:170598160506:web:4ef78a34c5969f792743c3',
    messagingSenderId: '170598160506',
    projectId: 'vibetalk-1994d',
    authDomain: 'vibetalk-1994d.firebaseapp.com',
    storageBucket: 'vibetalk-1994d.firebasestorage.app',
    measurementId: 'G-2LT78TQN36',
  );
}
